[package]
name = "ansible_utils"
version = "0.1.0"
revision = "2025"
authors = ["Brian Coca <devnull@spamhere.com>"]

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.module_utils]
path = "src/module_utils"

#[dependencies.config]
#path = "src/config"


[workspace]
# // members = ["src/config"]
members = ["src/module_utils"]
